pipeline{
    agent any
    stages{
        stage("checkout"){
            steps{
                echo "========executing checkout========"
                checkout scm
            }
        }            
        stage("build docker image"){
            steps{
                script{
                  echo "========executing settingup environment========"
                  bat 'docker build -t angular-app-jenkins-image:latest .'
                }
            }
        }
        
        stage("Deploy Docker Container"){
            steps{
                script{
                    
                bat 'docker run -d -p 5000:5000 --name flask-container angular-app-jenkins-image:latest'
                }
            }
        }
    }
}